### ISSUE TITLE
for some reason, getting an ImportError

### ISSUE THREAD

**Issue by jondot** [spacialdb/parse_fdw#2]
This is the traceback:

```
ERROR:  Error in python: ImportError
DETAIL:  Traceback (most recent call last):

      File "/usr/local/lib/python2.7/dist-packages/multicorn-1.2.4-py2.7-linux-x86_64.egg/multicorn/__init__.py", line 468, in get_class
        module = import_module(module_name)

      File "/usr/local/lib/python2.7/dist-packages/multicorn-1.2.4-py2.7-linux-x86_64.egg/multicorn/__init__.py", line 448, in import_module
        __import__(name)

      File "/usr/local/lib/python2.7/dist-packages/parse_fdw/parse_fdw.py", line 4, in <module>
        from parse_rest.connection import register

    ImportError: No module named connection
```

Running on Postgres 9.4, and I've verified all `pip` dependencies were installed, any idea why this still happens? 

Thanks!

**Comment by jondot** [comment]
Solved. need to explicitly `pip install` the current `parse_rest` like so:

```
$ pip install git+https://github.com/dgrtwo/ParsePy.git
```

which override the very old pypi version.

**Comment by jondot** [comment]
Just noticed the dependency in `setup.py` - I suggest to update it to current `parse_rest` - what do you think?

**Comment by kashif** [comment]
Yes... @jondot the issue is that i need the pull request dgrtwo/ParsePy#105 merged...
